language: ruby
cache: bundler

gemfile:
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails6.0.gemfile

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - bundle exec rake setup

script:
  - bundle exec rake

rvm:
  - 2.6.6
