version: '3.3'

services:
  app:
    build: '.'
    command: 'make test'
    platform: linux/amd64 # in order to old versions of v8 to compile in arm64
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    environment:
      BUNDLE_APP_CONFIG: /app/.bundle

